AllCops:
  Exclude:
    - Rakefile
    - bin/*
    - vendor/**/*
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - spec/userstack/**/*
    - userstack.gemspec

Metrics/LineLength:
  Max: 128
  Exclude:
    - spec/userstack/**/*

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
